config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :genres
  resources :authors
  resources :books
  resources :reviews
  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 400}
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :make_sure_signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @genres = Genre.paginate(page: params[:page], per_page: 10)
  end

  def show
    @genre = Genre.find_by(id: params[:id])
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new
    @genre.name = params[:genre][:name]
    @genre.description = params[:genre][:description]
    if @genre.save
      redirect_to genres_url, notice: "Created genre: #{@genre.name}"
    else
      render :new
    end
  end

  def edit
    @genre = Genre.find_by(id: params[:id])
  end

  def update
    @genre = Genre.find_by(id: params[:id])
    @genre.name = params[:genre][:name]
    @genre.description = params[:genre][:description]
    if @genre.save
      redirect_to genre_url(@genre), notice: "Genre was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    genre = Genre.find_by(id: params[:id])
    genre.destroy
    redirect_to genres_url, notice: 'Genre destroyed'
  end

end

app/views/genres/_form.html.erb
<%= form_for @genre do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <p><%= form.label :name %>
  <br>
  <%= form.text_field :name, size: 80, autofocus: true %>
  </p>

  <p><%= form.label :description %>
  <br>
  <%= form.text_area :description, rows: 4, cols: 80 %>
  </p>

  <%= form.submit %>
<% end %>

app/views/genres/edit.html.erb
<h2>Edit Genre</h2>

<%= render 'form' %>

app/views/genres/index.html.erb
<h1>
Genres
<small>
<%= link_to "New genre", new_genre_path %>
</small>
</h1>

<%= will_paginate %>
<% @genres.each do |genre| %>

    <h3><%= link_to genre.name, genre_path(genre.id) %></h3>

<% end %>

app/views/genres/new.html.erb
<h2>Add a New Genre</h2>

<%= render 'form' %>

app/views/genres/show.html.erb
<h1>
<%= @genre.name %>
<small>
  <%= link_to "Edit This Genre", edit_genre_path(@genre.id) %>
  <%= link_to "Delete This Genre", genre_path(@genre.id), :method => :delete %>
</small>
</h1>

<div class="details">
  <p><strong>Description:</strong> <%= @genre.description %></p>

  <p><strong>Books of this genre:</strong></p>

  <ul>
    <% books = Book.where(genre_id: @genre.id) %>
    <% books.each do |book| %>
      <li><%= link_to book.title, "/books/#{book.id}" %></li>
    <% end %>
  </ul>

</div>