config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :genres
  resources :authors
  resources :books
  resources :reviews
  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :roles
  has_many :books, :through => :roles

  validates :name, presence: true, length: { maximum: 100 }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :make_sure_signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @authors = Author.paginate(page: params[:page], per_page: 14)
  end

  def show
    @author = Author.find_by(id: params[:id])
    if @author == nil
      redirect_to authors_url
    end
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new
    @author.name = params[:author][:name]
    @author.image_url = params[:author][:image_url]
    if @author.save
      redirect_to authors_url, notice: "Author added!"
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find_by(id: params[:id])
  end

  def update
    @author = Author.find_by(id: params[:id])
    @author.name = params[:author][:name]
    @author.image_url = params[:author][:image_url]
    if @author.save
      redirect_to authors_url(@author), notice: "Updated author"
    else
      render :edit
    end
  end

  def destroy
    author = Author.find_by(id: params[:id])
    if author
      author.destroy
    end
    redirect_to author_url
  end

end

app/views/authors/_form.html.erb
<%= form_for @author do |form| %>

  <%= render 'shared/error_messages', object: form.object %>

  <p><%= form.label :name, "Name" %>
  <br>
  <%= form.text_field :name, size: 80, autofocus: true %></p>

  <%= form.label :image_url,  "Link to picture URL" %>
  <br>
  <%= form.text_field :image_url, size: 80 %>

  <br>
  <%= form.submit %>
<% end %>

app/views/authors/edit.html.erb
<h2>Edit Author</h2><h2><%= @author.name %></h2>

<%= render 'form' %>

app/views/authors/index.html.erb
<h1>
Authors
<small>
<%= link_to "New author", new_author_path %>
</small>
</h1>

<%= will_paginate %>
<% @authors.each do |author| %>

    <h3><%= link_to author.name, author_path(author.id) %></h3>

<% end %>

app/views/authors/new.html.erb
<h2>Add a New Author</h2>

<%= render 'form' %>

app/views/authors/show.html.erb
<h1>
  <%= @author.name %>
  <small>
    <%= link_to "Edit This Author", edit_author_path(@author.id) %>
    <%= link_to "Delete This Author", author_path(@author.id), :method => :delete %>
  </small>
</h1>

<div class="details">
<p><%= image_tag @author.image_url, class: 'pull-right' %></p>


<p><strong>Books by this author:<p><strong>

<ul>
  <% @author.books.each do |book| %>
    <li><%= link_to book.title, "/books/#{book.id}" %></li>
  <% end %>
</ul>

</div>