config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :genres
  resources :authors
  resources :books
  resources :reviews
  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :genre

  has_many :roles
  has_many :authors, :through => :roles
  has_many :reviews

  validates :title, presence: true, length: { maximum: 200 }
  validates :description, length: { maximum: 400}
  validates :year, numericality: {only_integer: true}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :make_sure_signed_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @books = Book.paginate(page: params[:page], per_page: 14)
    if params[:keyword].present?
      @books = @books.where("title LIKE ? OR year = ?", "%#{params[:keyword]}%", params[:keyword])
    end
  end

  def show
    @book = Book.find_by(id: params[:id])
    if @book == nil
      redirect_to books_url and return
    end
    @reviews = @book.reviews.paginate(:page => params[:page], per_page: 3)
    session["book_id"] = @book.id
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.title = params[:book][:title]
    @book.description = params[:book][:description]
    @book.image_url = params[:book][:image_url]
    @book.genre_id = params[:book][:genre_id]
    @book.year = params[:book][:year]
    if @book.save
      add_author_to_book
      redirect_to books_url, notice: "Book was successfully added"
    else
      render :new
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])
    @book.title = params[:book][:title]
    @book.description = params[:book][:description]
    @book.image_url = params[:book][:image_url]
    @book.genre_id = params[:book][:genre_id]
    @book.year = params[:book][:year]
    if @book.save
      add_author_to_book
      redirect_to books_url(@book), notice: "Book was successfully updated"
    else
      render :edit
    end
  end

  def add_author_to_book
    if params[:book][:authors].present?
      author = Author.find(params[:book][:authors])
      if author
        @book.authors << author
      end
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    if @book
      @book.destroy
    end
    redirect_to books_url
  end

end

app/views/books/_book.html.erb
<% poster_url = book ? book.image_url : 'http://dummyimage.com/600x400/000000/ffffff&text=ADD+NEW' %>
<% path = book ? book_path(book.id) : new_book_path %>

<div class="book-box">
  <%= link_to image_tag(poster_url), path %>
  <% if book %>
    <h3><%= link_to book.title, book_path(book.id) %></h3>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_for @book do |form| %>
  <%= render 'shared/error_messages', object: form.object %>

  <p><%= form.label :title %>
  <br>
  <%= form.text_field :title, size: 80, autofocus: true %></p>

  <p><%= form.label :genre_id, "Genre" %>
  <br>
  <%= form.collection_select :genre_id, Genre.all.order('name'), :id, :name %></p>
  <p><%= form.label :year %>
  <br>
  <%= form.number_field :year %></p>

  <%= form.label :image_url,  "Link to poster URL" %>
  <br>
  <%= form.text_field :image_url, size: 80 %>

  <p><%= form.label :description %>
  <br>
  <%= form.text_area :description, rows: 4, cols: 80 %></p>

  <p>
  <%= form.label :author_id, "Add an author" %>
  <br>
  <%= form.collection_select :authors,
        Author.where.not(id: @book.author_ids),
        :id, :name, include_blank: 'Select' %>
  </p>

  <%= form.submit %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit Book</h2><h2><%= @book.title %></h2>

<%= render 'form' %>

app/views/books/index.html.erb
<aside>
  <h3>Recommended For You</h3>
  <% if session["book_id"].present? and recommended = Book.find_by(id: session["book_id"]) %>
    <%= render recommended %>
  <% else %>
    <%= render Book.sample %>
  <% end %>
</aside>

<%= will_paginate %>
<div class="book-selections">
  <%= render 'book', book: nil %>
    <%= render @books %>
</div>

app/views/books/new.html.erb
<h2>Add a New Book</h2>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>
  <%= @book.title %>
  <small>
    <%= link_to "Edit This Book", edit_book_path(@book.id) %>
    <%= link_to "Delete This Book", book_path(@book.id), :method => :delete %>
  </small>
</h1>

<div class="details">

  <p><%= image_tag @book.image_url, class: 'pull-right' %></p>

  <p><strong>Genre: </strong>
    <% if @book.genre.present?%>
      <%= link_to @book.genre.name, "/genres/#{@book.genre.id}" %>
    <% else %>
      Unknown
    <% end %>
  </p>

  <p><strong>Released:</strong> <%= @book.year %></p>
  <p><strong>Description:</strong> <%= @book.description %></p>


  <p><strong>Authors: </strong></p>

  <ul>
    <% @book.authors.each do |author| %>
      <li><%= link_to author.name, author_path(author) %></li>
    <% end %>
  </ul>

  <br>

  <% if current_user = signed_in_user %>
    <h3>Add a Review</h3>
    <% review = Review.new %>
    <% review.user_id = current_user.id %>
    <% review.book_id = @book.id %>
    <%= render 'reviews/form', review: review %>
  <% else %>
    <h2>Only signed-in users can add reviews.</h2>
  <% end %>

  <br>
  <p><strong>Reviews</strong></p>
  <%= will_paginate @reviews %>
  <% @reviews.each do |review| %>
    <p><strong><%= review.user.name %></strong>
    <p>Rating: <%= review.rating %></p>
    <p>Comment: <%= review.comment %> </p>
    <br>
  <% end %>

</div>