config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :genres
  resources :authors
  resources :books
  resources :reviews
  resources :users

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreatReads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to "Books", books_path %></li>
      <li><%= link_to "Genres", genres_path %></li>
      <li><%= link_to "Authors", authors_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <%= form_tag books_url, :method => :get do %>
        <%= text_field_tag :keyword, '', placeholder: 'Search by title...' %>
      <% end %>
    </ul>
    <ul class="nav-right">
      <% if current_user = signed_in_user %>
        <li>Hello, <%= link_to current_user.name, user_path(current_user) %>!</li>
        <li><%= link_to "Sign Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Sign In", login_path %></li>
      <% end %>
    </ul>
  </nav>

  <div class="container">

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>